[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = "=1.0.2"
anchor-spl = "=1.0.2"
ephemeral-rollups-sdk = { git = "https://github.com/magicblock-labs/ephemeral-rollups-sdk.git", rev = "0fc4604157de51df28693e02e5a1a6a4a08c8a03", features = ["anchor", "access-control"] }
magicblock-magic-program-api = { version = "=0.10.1", default-features = false }
solana-sha256-hasher = "=3.1.0"
